version: 2

models:
 - name: stg_company
   description: Staged order data from the bootcamp dataset, focused on clerical information.
   columns: 
    - name: company_id
      description: Primary Key for Company
      tests:
       - unique
       - not_null

    - name: company_name
      description: Name of the Company
      tests:
       - not_null

    - name: address
      description: Date the order must arrive by

    - name: assignee_id
      description: Date that the order was shipped

    - name: details
      description: Customer Details

    - name: interaction_count
      description: Foreign Key for customer
      tests:
       - not_null

    - name: date_created
      description: Date Customer was created